user:
    resource: "@UserBundle/Resources/config/routing.xml"
    prefix:   /

article:
    resource: "@ArticleBundle/Resources/config/routing.xml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"